import type { ComplianceResult } from '@/lib/rules/types';

/**
 * Values both report renderers must agree on.
 *
 * The PDF is an HTML template and the DOCX is an object tree, so they cannot share a
 * layout. They *must* share the reference number, the timestamps and the wording of
 * the methodology and disclaimer — otherwise the same scan could be handed over twice
 * with two different reference numbers or two different accounts of how it was scored,
 * which is exactly the kind of discrepancy that gets a finding thrown out.
 */

const DATE_TIME = new Intl.DateTimeFormat('en-IN', {
  dateStyle: 'medium',
  timeStyle: 'short',
  timeZone: 'Asia/Kolkata',
});

/** `LM/3F9A1C2B8D` — the reference printed on every artefact for this scan. */
export function shortRef(scanId: string): string {
  return scanId.slice(-10).toUpperCase();
}

export function reportReference(scanId: string): string {
  return `LM/${shortRef(scanId)}`;
}

export function formatReportDateTime(value: Date | null | undefined): string {
  return value ? `${DATE_TIME.format(value)} IST` : '—';
}

/** The arithmetic behind the score, stated so the figure can be checked by hand. */
export function scoreFormulaText(compliance: ComplianceResult): string {
  const { applicableWeight, lostWeight } = compliance.breakdown;
  return `100 × (${applicableWeight} − ${lostWeight}) / ${applicableWeight} = ${compliance.score}`;
}

export function notAssessedCount(compliance: ComplianceResult): number {
  return compliance.breakdown.clausesEvaluated - compliance.breakdown.clausesApplicable;
}

/**
 * One sentence naming what was actually assessed.
 *
 * It belongs on the report because the two sources carry different evidential weight: a
 * photograph is the officer's own observation of a physical pack, whereas a listing
 * capture is a record of what a seller published at a URL on a date and can be edited
 * the next day. A reader must be able to tell which they are holding, so the URL is
 * printed rather than summarised.
 */
export function describeScanSource(scan: {
  source?: string | null;
  sourceUrl?: string | null;
}): string {
  if (scan.source === 'ECOMMERCE_LISTING') {
    return scan.sourceUrl
      ? `E-commerce product listing · ${scan.sourceUrl}`
      : 'E-commerce product listing (URL not recorded)';
  }
  return 'Photograph captured by the inspecting officer';
}

export const METHODOLOGY_STEPS = [
  'The label photograph was transcribed into a fixed set of declaration fields. The extractor is instructed to report absence rather than infer a plausible value, so a blank field means nothing was read at that position.',
  'Each declaration was then tested by an independent, deterministic rule function. No part of the compliance decision is made by the vision model.',
  'The score is a weighted deduction over the clauses that could actually be assessed. Clauses that could not be assessed are excluded from the denominator rather than counted as passes.',
] as const;

export const REPORT_DISCLAIMER =
  'This report is generated by an automated screening tool to assist a Legal Metrology Officer. ' +
  'Findings are based solely on what was visible in the submitted photograph and on the panel photographed; ' +
  'declarations printed on panels not captured in the image cannot be assessed. Rule codes prefixed "LM-PCR-" ' +
  'are internal identifiers for the clause referenced in each finding. This document is not by itself a notice, ' +
  'a determination or an order under the Legal Metrology Act, 2009, and requires verification and signature by ' +
  'the inspecting officer before any enforcement action is taken.';

export const REPORT_TITLE = 'Packaged Commodities Compliance Report';
export const REPORT_DEPARTMENT = 'Government of India · Department of Legal Metrology';
export const REPORT_STATUTE =
  'Legal Metrology Act, 2009 · Legal Metrology (Packaged Commodities) Rules, 2011';
